提交
hduhelp/backend_2023_freshman_task pull request #22
Opened 2023-10-07 11:41 UTC by ccstudyhyc

请问这次的提交方式是合格的么

2023-10-07 11:52 UTC, setcy commented
可以了。最好是里面文件加一个.md后缀。

2023-10-08 03:27 UTC, setcy approved these changes

2023-10-08 03:33 UTC, setcy commented
话说为什么你的git log里有别人的提交记录啊。。

2023-10-08 03:36 UTC, setcy requested changes
话说为什么你的git log里有别人的提交记录啊。。

2023-10-08 03:36 UTC, setcy commented on hhhyc/hhhycs
重命名为hhhycs.md

2023-10-08 09:39 UTC, ccstudyhyc commented
我把文件格式改成了 md （请问改成md有什么作用么）  但是为什么会有两个人参与 我也不知道  。。。

2023-10-08 09:42 UTC, setcy approved these changes

2023-10-08 09:43 UTC, setcy commented
md表示这个文件是文本文件。不然系统不知道你这是图片还是什么文件

2023-10-14 11:34 UTC, merged