feat : finish task
hduhelp/backend_2023_freshman_task pull request #24
Opened 2023-10-07 13:09 UTC by KQLXK

2023-10-07 13:10 UTC, setcy commented
go.mod和go.sum要在文件夹里面

2023-10-08 03:28 UTC, setcy requested changes
go.mod和go.sum要在新建的文件夹里面

2023-10-08 04:06 UTC, setcy approved these changes

2023-10-08 11:21 UTC, KQLXK commented
我这算是提交成功了吗

2023-10-08 11:23 UTC, setcy commented
> 我这算是提交成功了吗

是的

2023-10-08 11:23 UTC, KQLXK commented
好的好的

2023-10-08 11:24 UTC, KQLXK commented
我想问一下线下的展示是所有人都会去还是要根据这个代码筛选过

2023-10-08 15:06 UTC, setcy commented
> 我想问一下线下的展示是所有人都会去还是要根据这个代码筛选过

展示之前我们不会筛选，所以应该是所有人都会去。（但是可以自愿放弃然后不去）

2023-10-14 11:44 UTC, merged

2023-10-16 03:22 UTC, NX-Official commented
@KQLXK  你的名字 ❤️

2023-10-16 03:41 UTC, KQLXK commented
俞超



---- 回复的原邮件 ----
| 发件人 | Nick ***@***.***> |
| 日期 | 2023年10月16日 11:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [hduhelp/backend_2023_freshman_task] feat : finish task (PR #24) |

@KQLXK 你的名字 ❤️

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-10-16 15:58 UTC, KQLXK commented
面试结果出了吗